### PR TITLE
Test and prod deployment

### PR DESCRIPTION
**Pull request by TANguyen1893**

### CODE REVIEW

**Review by emmanue — APPROVED** [review]
Just for clarity, why are there sealed secrets here production/resources/argocd-notifications-sealed-secret.yaml and there  production/resources/argocd-sealed-secret.yaml  and is the sealing done manually or is there a script for that?

**Review by emmanue — APPROVED** [review]
I'm just seeing bulk pack consumer and kustomization in applications/overlays/development/,  is there a reason why there is no treetracker-contract-api.yaml file in there ? 
Other than that everything else looks good.

**Review by emmanue — APPROVED** [review]
Were there any issues with creationTimestamp in the  development/resources/argocd-notifications-sealed-secret.yaml ?
The rest looks good.

**Comment by TANguyen1893** [comment]
> Just for clarity, why are there sealed secrets here production/resources/argocd-notifications-sealed-secret.yaml and there production/resources/argocd-sealed-secret.yaml and is the sealing done manually or is there a script for that?

Yes, the sealed secrets are sealed manually.





> I'm just seeing bulk pack consumer and kustomization in applications/overlays/development/, is there a reason why there is no treetracker-contract-api.yaml file in there ? Other than that everything else looks good.

It was done in a previous PR

**Pull request merged**
